[tool.poetry]
name = "hash-code-2022"
version = "0.1.0"
description = ""
authors = ["lgelmi <lorenzo.gelmi@prima.it>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
